### ISSUE TITLE
App fail to start with "Error creating bean with name 'jiraAuthService'" 

### ISSUE THREAD

**Issue by val16384** [MikeSafonov/jira-telegram-bot#11]
As I understand its relate to OAuth integration with JIRA.

I have no idea what to write in oauth section of config .
Is it possible to use the  app without OAuth integration ?
Just for transmission JIRA webhooks to Telegram 

Error messages:

16:16:44.076 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
jira-telegram-bot_1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jiraAuthService' defined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/com/github/mikesafonov/jira/telegram/service/jira/JiraAuthService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jiraOAuthClient' defined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/com/github/mikesafonov/jira/telegram/service/jira/oauth/JiraOAuthClient.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jiraOAuthTokenFactory' defined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/com/github/mikesafonov/jira/telegram/service/jira/oauth/JiraOAuthTokenFactory.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.mikesafonov.jira.telegram.service.jira.oauth.JiraOAuthTokenFactory]: Constructor threw exception; nested exception is java.security.spec.InvalidKeySpecException: java.security.InvalidKeyException: IOException : Short read of DER length

16:21:54.265 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
jira-telegram-bot_1  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jiraAuthService' defined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/com/github/mikesafonov/jira/telegram/service/jira/JiraAuthService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jiraOAuthClient' defined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/com/github/mikesafonov/jira/telegram/service/jira/oauth/JiraOAuthClient.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jiraOAuthTokenFactory' defined in URL [jar:file:/app/app.jar!/BOOT-INF/classes!/com/github/mikesafonov/jira/telegram/service/jira/oauth/JiraOAuthTokenFactory.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.github.mikesafonov.jira.telegram.service.jira.oauth.JiraOAuthTokenFactory]: Constructor threw exception; nested exception is java.lang.IllegalArgumentException: com.google.common.io.BaseEncoding$DecodingException: Invalid input length 5

**Comment by MikeSafonov** [comment]
This is a bug. Will be fixed in future release. 

Please use [latest](https://github.com/MikeSafonov/jira-telegram-bot/releases/tag/v1.0.1) release. Its not depends on jira oauth.

**Comment by MikeSafonov** [comment]
Fixed in [v1.1.0](https://github.com/MikeSafonov/jira-telegram-bot/releases/tag/v1.1.0)

**Comment by val16384** [comment]
Thank you!
